networks:
  default:
    name: ${NETWORK:-traefik}

volumes:
  adguard_data:
  adguard_conf:
  portainer_data:


services:
  adguard:
    image: adguard/adguardhome
    restart: unless-stopped
    command: --web-addr 0.0.0.0:80
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.service=adguard
      - traefik.http.services.adguard.loadbalancer.server.port=80

  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    command: |-
      --api.insecure=true
      --entrypoints.http.address=:80
      --entrypoints.http.asdefault=true
      --entrypoints.https.address=:443
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --providers.docker.defaultrule='Host(`{{ index .Labels "com.docker.compose.service" }}.{{ env "TLD" }}`)'
    environment:
      - TLD=${TLD:-home}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.service=traefik
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  portainer:
    image: portainer/portainer-ee:2.21.4
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000

  rancher:
    image: rancher/server:stable
    restart: unless-stopped
    profiles:
      - all
      - rancher
    labels:
      - traefik.enable=true
      - traefik.http.routers.rancher.service=rancher
      - traefik.http.services.rancher.loadbalancer.server.port=8080

  excalidraw:
    image: excalidraw/excalidraw
    restart: unless-stopped
    profiles:
      - all
      - excalidraw
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.service=excalidraw
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
