services:
  excalidraw:
    image: excalidraw/excalidraw
    profiles:
      - excalidraw
    labels:
      - traefik.enable=true
      - traefik.http.routers.excalidraw.service=excalidraw
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK:-traefik}
    external: true
